version: '3.8'

services:
  # Сервис базы данных
  postgres_db:
    image: postgres:15-alpine
    container_name: marketplace_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Сервис бэкенда
  api_backend:
    build: .
    container_name: marketplace_api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:changeme@postgres_db:5432/marketplace?schema=public
      - JWT_SECRET=super_secret_key_123
      - PORT=3001
    depends_on:
      - postgres_db

volumes:
  pgdata: